### ISSUE TITLE
Invalid path to cuDNN toolkit.

### ISSUE THREAD

**Issue by augre** [dougnd/palmetto-scripts#2]
Hi,

I tried installing tensorflow on palmetto following your tutorial and got this error:
```
Do you wish to build TensorFlow with OpenCL support? [y/N] 
No OpenCL support will be enabled for TensorFlow
Invalid path to cuDNN  toolkit. Neither of the following two files can be found:
/home/xrzheng/usr/local/lib64/libcudnn.so.4.0.7
/home/xrzheng/usr/local/libcudnn.so.4.0.7
.4.0.7
```

Do you know what the issue is?

Also, is this still the preferred way of installing tensorflow?

Thanks!

**Comment by dougnd** [comment]
Well I'm not sure it was ever a "preferred" way haha, but it did work at one point.  It does seem like it is not working now though.  I'm taking a look at it.  If nothing else, I'm sure I can change the script so it grabs a particular version known to work (probably 0.9),  but I'm guessing you'd like 1.0 to work?

**Comment by dougnd** [comment]
Ok, I talked to other people who use tensorflow on palmetto.  There is a better solution than using dinstall/palmetto-scripts .  See the [README](https://github.com/dougnd/palmetto-scripts/blob/master/README.md#update)

**Comment by augre** [comment]
Thanks!
